"""Gazetteer: countries, states/regions and cities, with the aliases people actually type.

Coverage is deliberate, not exhaustive: every Indian state and union territory and its major
cities; states/provinces for the US, Canada, UK, Australia and Germany; and the cities where
tech jobs cluster elsewhere. Unknown places are still kept (as typed) when the surrounding
text identifies them, so the gazetteer improves results but never drops data.
"""

# ISO 3166-1 alpha-2 -> (display name, aliases incl. common alpha-3 codes)
COUNTRIES: dict[str, tuple[str, tuple[str, ...]]] = {
    "IN": ("India", ("ind", "bharat")),
    "US": ("United States", ("usa", "us", "u.s.", "u.s.a.", "united states of america", "america")),
    "GB": ("United Kingdom", ("uk", "u.k.", "gbr", "great britain", "britain")),
    "CA": ("Canada", ("can",)),
    "AU": ("Australia", ("aus",)),
    "DE": ("Germany", ("deu", "deutschland")),
    "FR": ("France", ("fra",)),
    "NL": ("Netherlands", ("nld", "the netherlands", "holland")),
    "IE": ("Ireland", ("irl", "republic of ireland")),
    "ES": ("Spain", ("esp", "españa")),
    "PT": ("Portugal", ("prt",)),
    "IT": ("Italy", ("ita", "italia")),
    "PL": ("Poland", ("pol",)),
    "SE": ("Sweden", ("swe",)),
    "DK": ("Denmark", ("dnk",)),
    "NO": ("Norway", ("nor",)),
    "FI": ("Finland", ("fin",)),
    "CH": ("Switzerland", ("che",)),
    "AT": ("Austria", ("aut",)),
    "BE": ("Belgium", ("bel",)),
    "CZ": ("Czech Republic", ("cze", "czechia")),
    "RO": ("Romania", ("rou",)),
    "HU": ("Hungary", ("hun",)),
    "GR": ("Greece", ("grc",)),
    "UA": ("Ukraine", ("ukr",)),
    "EE": ("Estonia", ("est",)),
    "LT": ("Lithuania", ("ltu",)),
    "LV": ("Latvia", ("lva",)),
    "RS": ("Serbia", ("srb",)),
    "BG": ("Bulgaria", ("bgr",)),
    "HR": ("Croatia", ("hrv",)),
    "LU": ("Luxembourg", ("lux",)),
    "IL": ("Israel", ("isr",)),
    "AE": ("United Arab Emirates", ("uae", "are", "u.a.e.")),
    "SA": ("Saudi Arabia", ("sau", "ksa")),
    "QA": ("Qatar", ("qat",)),
    "TR": ("Turkey", ("tur", "türkiye", "turkiye")),
    "EG": ("Egypt", ("egy",)),
    "ZA": ("South Africa", ("zaf",)),
    "NG": ("Nigeria", ("nga",)),
    "KE": ("Kenya", ("ken",)),
    "SG": ("Singapore", ("sgp",)),
    "JP": ("Japan", ("jpn",)),
    "KR": ("South Korea", ("kor", "korea", "republic of korea")),
    "CN": ("China", ("chn",)),
    "HK": ("Hong Kong", ("hkg", "hong kong sar")),
    "TW": ("Taiwan", ("twn",)),
    "PH": ("Philippines", ("phl",)),
    "ID": ("Indonesia", ("idn",)),
    "MY": ("Malaysia", ("mys",)),
    "TH": ("Thailand", ("tha",)),
    "VN": ("Vietnam", ("vnm", "viet nam")),
    "PK": ("Pakistan", ("pak",)),
    "BD": ("Bangladesh", ("bgd",)),
    "LK": ("Sri Lanka", ("lka",)),
    "NP": ("Nepal", ("npl",)),
    "NZ": ("New Zealand", ("nzl",)),
    "BR": ("Brazil", ("bra", "brasil")),
    "MX": ("Mexico", ("mex", "méxico")),
    "AR": ("Argentina", ("arg",)),
    "CO": ("Colombia", ("col",)),
    "CL": ("Chile", ("chl",)),
    "PE": ("Peru", ("per",)),
    "UY": ("Uruguay", ("ury",)),
    "CR": ("Costa Rica", ("cri",)),
    "SI": ("Slovenia", ("svn",)),
    "IS": ("Iceland", ("isl",)),
    "KH": ("Cambodia", ("khm",)),
    "CY": ("Cyprus", ("cyp",)),
    "MT": ("Malta", ("mlt",)),
}

# Country -> {canonical state/region: (aliases, abbreviations)}. Abbreviations only match as
# exact upper-case tokens next to a place in that country ("Noida, UP"; "Austin, TX").
STATES: dict[str, dict[str, tuple[tuple[str, ...], tuple[str, ...]]]] = {
    "IN": {
        # 28 states
        "Andhra Pradesh": ((), ("AP",)),
        "Arunachal Pradesh": ((), ("AR",)),
        "Assam": ((), ("AS",)),
        "Bihar": ((), ("BR",)),
        "Chhattisgarh": (("chattisgarh",), ("CG", "CT")),
        "Goa": ((), ("GA",)),
        "Gujarat": ((), ("GJ",)),
        "Haryana": ((), ("HR",)),
        "Himachal Pradesh": ((), ("HP",)),
        "Jharkhand": ((), ("JH",)),
        "Karnataka": ((), ("KA",)),
        "Kerala": ((), ("KL",)),
        "Madhya Pradesh": ((), ("MP",)),
        "Maharashtra": ((), ("MH",)),
        "Manipur": ((), ("MN",)),
        "Meghalaya": ((), ("ML",)),
        "Mizoram": ((), ("MZ",)),
        "Nagaland": ((), ("NL",)),
        "Odisha": (("orissa",), ("OD", "OR")),
        "Punjab": ((), ("PB",)),
        "Rajasthan": ((), ("RJ",)),
        "Sikkim": ((), ("SK",)),
        "Tamil Nadu": (("tamilnadu",), ("TN",)),
        "Telangana": ((), ("TG", "TS")),
        "Tripura": ((), ("TR",)),
        "Uttar Pradesh": ((), ("UP",)),
        "Uttarakhand": (("uttaranchal",), ()),  # its code "UK" collides with the country
        "West Bengal": ((), ("WB",)),
        # 8 union territories
        "Andaman and Nicobar Islands": (
            ("andaman & nicobar islands", "andaman and nicobar"),
            ("AN",),
        ),
        "Chandigarh": ((), ("CH",)),
        "Dadra and Nagar Haveli and Daman and Diu": (
            ("dadra and nagar haveli", "daman and diu", "dnh and dd"),
            ("DH", "DN", "DD"),
        ),
        "Delhi": (
            ("nct of delhi", "national capital territory of delhi", "delhi ncr", "ncr"),
            ("DL",),
        ),
        "Jammu and Kashmir": (("jammu & kashmir", "j&k"), ("JK",)),
        "Ladakh": ((), ("LA",)),
        "Lakshadweep": ((), ("LD",)),
        "Puducherry": (("pondicherry",), ("PY",)),
    },
    "US": {
        "Alabama": ((), ("AL",)), "Alaska": ((), ("AK",)), "Arizona": ((), ("AZ",)),
        "Arkansas": ((), ("AR",)), "California": (("calif",), ("CA",)), "Colorado": ((), ("CO",)),
        "Connecticut": ((), ("CT",)), "Delaware": ((), ("DE",)),
        "District of Columbia": (("washington dc", "washington d.c.", "d.c.", "dc"), ("DC",)),
        "Florida": ((), ("FL",)), "Georgia": ((), ("GA",)), "Hawaii": ((), ("HI",)),
        "Idaho": ((), ("ID",)), "Illinois": ((), ("IL",)), "Indiana": ((), ("IN",)),
        "Iowa": ((), ("IA",)), "Kansas": ((), ("KS",)), "Kentucky": ((), ("KY",)),
        "Louisiana": ((), ("LA",)), "Maine": ((), ("ME",)), "Maryland": ((), ("MD",)),
        "Massachusetts": ((), ("MA",)), "Michigan": ((), ("MI",)), "Minnesota": ((), ("MN",)),
        "Mississippi": ((), ("MS",)), "Missouri": ((), ("MO",)), "Montana": ((), ("MT",)),
        "Nebraska": ((), ("NE",)), "Nevada": ((), ("NV",)), "New Hampshire": ((), ("NH",)),
        "New Jersey": (("north jersey",), ("NJ",)), "New Mexico": ((), ("NM",)),
        "New York": ((), ("NY",)), "North Carolina": ((), ("NC",)), "North Dakota": ((), ("ND",)),
        "Ohio": ((), ("OH",)), "Oklahoma": ((), ("OK",)), "Oregon": ((), ("OR",)),
        "Pennsylvania": ((), ("PA",)), "Rhode Island": ((), ("RI",)),
        "South Carolina": ((), ("SC",)), "South Dakota": ((), ("SD",)), "Tennessee": ((), ("TN",)),
        "Texas": ((), ("TX",)), "Utah": ((), ("UT",)), "Vermont": ((), ("VT",)),
        "Virginia": ((), ("VA",)), "Washington": ((), ("WA",)), "West Virginia": ((), ("WV",)),
        "Wisconsin": ((), ("WI",)), "Wyoming": ((), ("WY",)),
    },
    "CA": {
        "Alberta": ((), ("AB",)), "British Columbia": ((), ("BC",)), "Manitoba": ((), ("MB",)),
        "New Brunswick": ((), ("NB",)), "Newfoundland and Labrador": (("newfoundland",), ("NL",)),
        "Nova Scotia": ((), ("NS",)), "Ontario": ((), ("ON",)),
        "Prince Edward Island": ((), ("PE", "PEI")), "Quebec": (("québec",), ("QC",)),
        "Saskatchewan": ((), ("SK",)), "Northwest Territories": ((), ("NT",)),
        "Nunavut": ((), ("NU",)), "Yukon": ((), ("YT",)),
    },
    "GB": {
        "England": ((), ()), "Scotland": ((), ()), "Wales": ((), ()),
        "Northern Ireland": ((), ("NI",)),
    },
    "AU": {
        "New South Wales": ((), ("NSW",)), "Victoria": ((), ("VIC",)),
        "Queensland": ((), ("QLD",)), "Western Australia": ((), ("WA",)),
        "South Australia": ((), ("SA",)), "Tasmania": ((), ("TAS",)),
        "Australian Capital Territory": ((), ("ACT",)), "Northern Territory": ((), ("NT",)),
    },
    "DE": {
        "Baden-Württemberg": (("baden-wurttemberg", "baden wurttemberg"), ("BW",)),
        "Bavaria": (("bayern",), ("BY",)), "Berlin": ((), ("BE",)), "Brandenburg": ((), ("BB",)),
        "Bremen": ((), ("HB",)), "Hamburg": ((), ("HH",)), "Hesse": (("hessen",), ("HE",)),
        "Lower Saxony": (("niedersachsen",), ("NI",)),
        "Mecklenburg-Vorpommern": ((), ("MV",)),
        "North Rhine-Westphalia": (("nordrhein-westfalen", "nrw"), ("NW",)),
        "Rhineland-Palatinate": (("rheinland-pfalz",), ("RP",)), "Saarland": ((), ("SL",)),
        "Saxony": (("sachsen",), ("SN",)), "Saxony-Anhalt": (("sachsen-anhalt",), ("ST",)),
        "Schleswig-Holstein": ((), ("SH",)), "Thuringia": (("thüringen", "thuringen"), ("TH",)),
    },
}  # fmt: skip

# Canonical city -> (country, state or None, aliases)
CITIES: dict[str, tuple[str, str | None, tuple[str, ...]]] = {
    # --- India ---
    "Bengaluru": ("IN", "Karnataka", ("bangalore", "bengaluru urban", "bangalore urban", "blr")),
    "Mysuru": ("IN", "Karnataka", ("mysore",)),
    "Mangaluru": ("IN", "Karnataka", ("mangalore",)),
    "Hubballi": ("IN", "Karnataka", ("hubli", "hubli-dharwad")),
    "Mumbai": ("IN", "Maharashtra", ("bombay", "mumbai suburban", "greater mumbai")),
    "Navi Mumbai": ("IN", "Maharashtra", ()),
    "Thane": ("IN", "Maharashtra", ()),
    "Pune": ("IN", "Maharashtra", ("poona",)),
    "Nagpur": ("IN", "Maharashtra", ()),
    "Nashik": ("IN", "Maharashtra", ("nasik",)),
    "Chhatrapati Sambhajinagar": ("IN", "Maharashtra", ("aurangabad",)),
    "New Delhi": ("IN", "Delhi", ()),
    "Delhi": ("IN", "Delhi", ()),
    "Gurugram": ("IN", "Haryana", ("gurgaon",)),
    "Faridabad": ("IN", "Haryana", ()),
    "Panchkula": ("IN", "Haryana", ()),
    "Noida": ("IN", "Uttar Pradesh", ()),
    "Greater Noida": ("IN", "Uttar Pradesh", ()),
    "Ghaziabad": ("IN", "Uttar Pradesh", ()),
    "Lucknow": ("IN", "Uttar Pradesh", ()),
    "Kanpur": ("IN", "Uttar Pradesh", ()),
    "Agra": ("IN", "Uttar Pradesh", ()),
    "Varanasi": ("IN", "Uttar Pradesh", ("benares", "banaras")),
    "Prayagraj": ("IN", "Uttar Pradesh", ("allahabad",)),
    "Meerut": ("IN", "Uttar Pradesh", ()),
    "Hyderabad": ("IN", "Telangana", ("secunderabad", "cyberabad")),
    "Warangal": ("IN", "Telangana", ()),
    "Chennai": ("IN", "Tamil Nadu", ("madras",)),
    "Coimbatore": ("IN", "Tamil Nadu", ()),
    "Madurai": ("IN", "Tamil Nadu", ()),
    "Tiruchirappalli": ("IN", "Tamil Nadu", ("trichy", "tiruchirapalli")),
    "Salem": ("IN", "Tamil Nadu", ()),
    "Kolkata": ("IN", "West Bengal", ("calcutta",)),
    "Durgapur": ("IN", "West Bengal", ()),
    "Siliguri": ("IN", "West Bengal", ()),
    "Ahmedabad": ("IN", "Gujarat", ("amdavad",)),
    "Gandhinagar": ("IN", "Gujarat", ("gift city",)),
    "Surat": ("IN", "Gujarat", ()),
    "Vadodara": ("IN", "Gujarat", ("baroda",)),
    "Rajkot": ("IN", "Gujarat", ()),
    "Jaipur": ("IN", "Rajasthan", ()),
    "Jodhpur": ("IN", "Rajasthan", ()),
    "Udaipur": ("IN", "Rajasthan", ()),
    "Kota": ("IN", "Rajasthan", ()),
    "Kochi": ("IN", "Kerala", ("cochin", "ernakulam", "kochi infopark")),
    "Thiruvananthapuram": ("IN", "Kerala", ("trivandrum",)),
    "Kozhikode": ("IN", "Kerala", ("calicut",)),
    "Thrissur": ("IN", "Kerala", ("trichur",)),
    "Chandigarh": ("IN", "Chandigarh", ()),
    "Mohali": ("IN", "Punjab", ("sas nagar", "sahibzada ajit singh nagar")),
    "Ludhiana": ("IN", "Punjab", ()),
    "Amritsar": ("IN", "Punjab", ()),
    "Jalandhar": ("IN", "Punjab", ()),
    "Indore": ("IN", "Madhya Pradesh", ()),
    "Bhopal": ("IN", "Madhya Pradesh", ()),
    "Gwalior": ("IN", "Madhya Pradesh", ()),
    "Jabalpur": ("IN", "Madhya Pradesh", ()),
    "Bhubaneswar": ("IN", "Odisha", ("bhubaneshwar",)),
    "Cuttack": ("IN", "Odisha", ()),
    "Visakhapatnam": ("IN", "Andhra Pradesh", ("vizag", "vishakhapatnam")),
    "Vijayawada": ("IN", "Andhra Pradesh", ()),
    "Guntur": ("IN", "Andhra Pradesh", ()),
    "Tirupati": ("IN", "Andhra Pradesh", ()),
    "Amaravati": ("IN", "Andhra Pradesh", ()),
    "Patna": ("IN", "Bihar", ()),
    "Ranchi": ("IN", "Jharkhand", ()),
    "Jamshedpur": ("IN", "Jharkhand", ()),
    "Raipur": ("IN", "Chhattisgarh", ()),
    "Bhilai": ("IN", "Chhattisgarh", ()),
    "Guwahati": ("IN", "Assam", ("gauhati",)),
    "Dehradun": ("IN", "Uttarakhand", ("dehra dun",)),
    "Haridwar": ("IN", "Uttarakhand", ()),
    "Shimla": ("IN", "Himachal Pradesh", ("simla",)),
    "Dharamshala": ("IN", "Himachal Pradesh", ("dharamsala",)),
    "Bir": ("IN", "Himachal Pradesh", ("bir billing",)),
    "Panaji": ("IN", "Goa", ("panjim",)),
    "Margao": ("IN", "Goa", ("madgaon",)),
    "Srinagar": ("IN", "Jammu and Kashmir", ()),
    "Jammu": ("IN", "Jammu and Kashmir", ()),
    "Leh": ("IN", "Ladakh", ()),
    "Puducherry": ("IN", "Puducherry", ("pondicherry",)),
    "Imphal": ("IN", "Manipur", ()),
    "Shillong": ("IN", "Meghalaya", ()),
    "Aizawl": ("IN", "Mizoram", ()),
    "Kohima": ("IN", "Nagaland", ()),
    "Agartala": ("IN", "Tripura", ()),
    "Gangtok": ("IN", "Sikkim", ()),
    "Itanagar": ("IN", "Arunachal Pradesh", ()),
    "Port Blair": ("IN", "Andaman and Nicobar Islands", ("sri vijaya puram",)),
    "Silvassa": ("IN", "Dadra and Nagar Haveli and Daman and Diu", ()),
    "Kavaratti": ("IN", "Lakshadweep", ()),
    # --- United States ---
    "San Francisco": (
        "US",
        "California",
        ("sf", "san francisco bay area", "bay area", "sf bay area", "sf bay"),
    ),
    "San Jose": ("US", "California", ()),
    "Santa Clara": ("US", "California", ()),
    "Sunnyvale": ("US", "California", ()),
    "Mountain View": ("US", "California", ()),
    "Palo Alto": ("US", "California", ()),
    "Menlo Park": ("US", "California", ()),
    "Redwood City": ("US", "California", ()),
    "Foster City": ("US", "California", ()),
    "San Mateo": ("US", "California", ()),
    "Cupertino": ("US", "California", ()),
    "Oakland": ("US", "California", ()),
    "Berkeley": ("US", "California", ()),
    "Los Angeles": ("US", "California", ("la",)),
    "Santa Monica": ("US", "California", ()),
    "Irvine": ("US", "California", ()),
    "San Diego": ("US", "California", ()),
    "Sacramento": ("US", "California", ()),
    "New York": ("US", "New York", ("new york city", "nyc", "manhattan", "brooklyn", "queens")),
    "Seattle": ("US", "Washington", ()),
    "Bellevue": ("US", "Washington", ()),
    "Redmond": ("US", "Washington", ()),
    "Kirkland": ("US", "Washington", ()),
    "Washington": ("US", "District of Columbia", ("washington dc", "washington d.c.")),
    "Arlington": ("US", "Virginia", ()),
    "Reston": ("US", "Virginia", ()),
    "Crystal City": ("US", "Virginia", ()),
    "McLean": ("US", "Virginia", ()),
    "Boston": ("US", "Massachusetts", ()),
    "Cambridge": ("US", "Massachusetts", ()),
    "Austin": ("US", "Texas", ()),
    "Dallas": ("US", "Texas", ()),
    "Houston": ("US", "Texas", ()),
    "San Antonio": ("US", "Texas", ()),
    "Plano": ("US", "Texas", ()),
    "Chicago": ("US", "Illinois", ()),
    "Denver": ("US", "Colorado", ()),
    "Boulder": ("US", "Colorado", ()),
    "Atlanta": ("US", "Georgia", ()),
    "Miami": ("US", "Florida", ()),
    "Tampa": ("US", "Florida", ()),
    "Orlando": ("US", "Florida", ()),
    "Phoenix": ("US", "Arizona", ()),
    "Scottsdale": ("US", "Arizona", ()),
    "Salt Lake City": ("US", "Utah", ()),
    "Lehi": ("US", "Utah", ()),
    "Portland": ("US", "Oregon", ()),
    "Philadelphia": ("US", "Pennsylvania", ()),
    "Pittsburgh": ("US", "Pennsylvania", ()),
    "Minneapolis": ("US", "Minnesota", ()),
    "Detroit": ("US", "Michigan", ()),
    "Ann Arbor": ("US", "Michigan", ()),
    "Nashville": ("US", "Tennessee", ()),
    "Raleigh": ("US", "North Carolina", ()),
    "Durham": ("US", "North Carolina", ()),
    "Charlotte": ("US", "North Carolina", ()),
    "St. Louis": ("US", "Missouri", ("saint louis", "st louis")),
    "Kansas City": ("US", "Missouri", ()),
    "Columbus": ("US", "Ohio", ()),
    "Cincinnati": ("US", "Ohio", ()),
    "Indianapolis": ("US", "Indiana", ()),
    "Las Vegas": ("US", "Nevada", ()),
    "Baltimore": ("US", "Maryland", ()),
    "Jersey City": ("US", "New Jersey", ()),
    "Newark": ("US", "New Jersey", ()),
    "Stamford": ("US", "Connecticut", ()),
    "Madison": ("US", "Wisconsin", ()),
    "Burlington": ("US", "Vermont", ()),
    # --- Canada ---
    "Toronto": ("CA", "Ontario", ()),
    "Ottawa": ("CA", "Ontario", ()),
    "Waterloo": ("CA", "Ontario", ("kitchener-waterloo", "kitchener")),
    "Vancouver": ("CA", "British Columbia", ()),
    "Victoria": ("CA", "British Columbia", ()),
    "Montreal": ("CA", "Quebec", ("montréal",)),
    "Quebec City": ("CA", "Quebec", ("québec city",)),
    "Calgary": ("CA", "Alberta", ()),
    "Edmonton": ("CA", "Alberta", ()),
    "Winnipeg": ("CA", "Manitoba", ()),
    "Halifax": ("CA", "Nova Scotia", ()),
    # --- United Kingdom ---
    "London": ("GB", "England", ("greater london", "city of london")),
    "Manchester": ("GB", "England", ()),
    "Birmingham": ("GB", "England", ()),
    "Leeds": ("GB", "England", ()),
    "Bristol": ("GB", "England", ()),
    "Oxford": ("GB", "England", ()),
    "Reading": ("GB", "England", ()),
    "Newcastle": ("GB", "England", ("newcastle upon tyne",)),
    "Edinburgh": ("GB", "Scotland", ()),
    "Glasgow": ("GB", "Scotland", ()),
    "Cardiff": ("GB", "Wales", ()),
    "Belfast": ("GB", "Northern Ireland", ()),
    # --- Australia ---
    "Sydney": ("AU", "New South Wales", ()),
    "Melbourne": ("AU", "Victoria", ()),
    "Brisbane": ("AU", "Queensland", ()),
    "Perth": ("AU", "Western Australia", ()),
    "Adelaide": ("AU", "South Australia", ()),
    "Canberra": ("AU", "Australian Capital Territory", ()),
    "Hobart": ("AU", "Tasmania", ()),
    # --- Germany ---
    "Berlin": ("DE", "Berlin", ()),
    "Munich": ("DE", "Bavaria", ("münchen", "munchen")),
    "Hamburg": ("DE", "Hamburg", ()),
    "Frankfurt": ("DE", "Hesse", ("frankfurt am main",)),
    "Cologne": ("DE", "North Rhine-Westphalia", ("köln", "koln")),
    "Düsseldorf": ("DE", "North Rhine-Westphalia", ("dusseldorf",)),
    "Stuttgart": ("DE", "Baden-Württemberg", ()),
    "Leipzig": ("DE", "Saxony", ()),
    "Dresden": ("DE", "Saxony", ()),
    "Nuremberg": ("DE", "Bavaria", ("nürnberg", "nurnberg")),
    # --- elsewhere (country only) ---
    "Paris": ("FR", None, ()), "Lyon": ("FR", None, ()),
    "Amsterdam": ("NL", None, ()), "Rotterdam": ("NL", None, ()),
    "Utrecht": ("NL", None, ()), "Eindhoven": ("NL", None, ()),
    "Dublin": ("IE", None, ()), "Cork": ("IE", None, ()),
    "Madrid": ("ES", None, ()), "Barcelona": ("ES", None, ()),
    "Lisbon": ("PT", None, ("lisboa",)), "Porto": ("PT", None, ()),
    "Milan": ("IT", None, ("milano",)), "Rome": ("IT", None, ("roma",)),
    "Warsaw": ("PL", None, ("warszawa",)), "Krakow": ("PL", None, ("kraków",)),
    "Wroclaw": ("PL", None, ("wrocław",)),
    "Stockholm": ("SE", None, ()), "Copenhagen": ("DK", None, ()),
    "Oslo": ("NO", None, ()), "Helsinki": ("FI", None, ()),
    "Zurich": ("CH", None, ("zürich",)), "Geneva": ("CH", None, ()),
    "Vienna": ("AT", None, ("wien",)), "Brussels": ("BE", None, ()),
    "Prague": ("CZ", None, ()), "Bucharest": ("RO", None, ()), "Budapest": ("HU", None, ()),
    "Athens": ("GR", None, ()), "Kyiv": ("UA", None, ("kiev",)), "Tallinn": ("EE", None, ()),
    "Vilnius": ("LT", None, ()), "Belgrade": ("RS", None, ()), "Sofia": ("BG", None, ()),
    "Tel Aviv": ("IL", None, ("tel aviv-yafo",)), "Haifa": ("IL", None, ()),
    "Dubai": ("AE", None, ()), "Abu Dhabi": ("AE", None, ()),
    "Riyadh": ("SA", None, ()), "Doha": ("QA", None, ()), "Istanbul": ("TR", None, ()),
    "Cairo": ("EG", None, ()), "Johannesburg": ("ZA", None, ()), "Cape Town": ("ZA", None, ()),
    "Lagos": ("NG", None, ()), "Nairobi": ("KE", None, ()),
    "Singapore": ("SG", None, ()), "Tokyo": ("JP", None, ()), "Osaka": ("JP", None, ()),
    "Seoul": ("KR", None, ()), "Shanghai": ("CN", None, ()), "Beijing": ("CN", None, ()),
    "Shenzhen": ("CN", None, ()), "Hong Kong": ("HK", None, ()), "Taipei": ("TW", None, ()),
    "Manila": ("PH", None, ()), "Jakarta": ("ID", None, ()), "Kuala Lumpur": ("MY", None, ()),
    "Bangkok": ("TH", None, ()), "Ho Chi Minh City": ("VN", None, ("saigon",)),
    "Hanoi": ("VN", None, ()), "Karachi": ("PK", None, ()), "Lahore": ("PK", None, ()),
    "Dhaka": ("BD", None, ()), "Colombo": ("LK", None, ()), "Kathmandu": ("NP", None, ()),
    "Auckland": ("NZ", None, ()), "Wellington": ("NZ", None, ()),
    "São Paulo": ("BR", None, ("sao paulo",)), "Rio de Janeiro": ("BR", None, ()),
    "Mexico City": ("MX", None, ("cdmx", "ciudad de méxico")), "Guadalajara": ("MX", None, ()),
    "Buenos Aires": ("AR", None, ()), "Bogotá": ("CO", None, ("bogota",)),
    "Santiago": ("CL", None, ()), "Lima": ("PE", None, ()), "Montevideo": ("UY", None, ()),
    "San José": ("CR", None, ()),
    "Ljubljana": ("SI", None, ()), "Reykjavík": ("IS", None, ("reykjavik",)),
    "Phnom Penh": ("KH", None, ()), "Limassol": ("CY", None, ()), "Valletta": ("MT", None, ()),
}  # fmt: skip

# Metro areas people search as one place: name -> (country, member cities, aliases).
# Members span states (Delhi NCR = Delhi + Haryana + Uttar Pradesh), which is why a city
# filter alone can't express them.
METROS: dict[str, tuple[str, tuple[str, ...], tuple[str, ...]]] = {
    "Delhi NCR": (
        "IN",
        ("Delhi", "New Delhi", "Noida", "Greater Noida", "Gurugram", "Ghaziabad", "Faridabad"),
        ("ncr", "delhi ncr", "delhi-ncr", "national capital region"),
    ),
    "Mumbai Metropolitan Region": (
        "IN",
        ("Mumbai", "Navi Mumbai", "Thane"),
        ("mmr", "mumbai mmr", "greater mumbai region"),
    ),
    "San Francisco Bay Area": (
        "US",
        (
            "San Francisco", "San Jose", "Santa Clara", "Sunnyvale", "Mountain View",
            "Palo Alto", "Menlo Park", "Redwood City", "Foster City", "San Mateo",
            "Cupertino", "Oakland", "Berkeley",
        ),
        ("bay area", "sf bay area", "silicon valley"),
    ),
}  # fmt: skip
