"""Coding practice: problems, running and submitting code, and question-bank admin."""

import json
import time
import uuid
from collections import defaultdict, deque
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

import structlog
from sqlalchemy import case, func, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.core.errors import AppError, ConflictError, NotFoundError
from app.db.models import (
    Difficulty,
    Language,
    Question,
    QuestionStatus,
    QuestionTemplate,
    Submission,
    TestCase,
    User,
    Verdict,
)
from app.db.session import session_factory
from app.modules.coding.grading import Grade, grade
from app.modules.coding.languages import DEFAULT_LANGUAGES, STARTERS
from app.workers.runtime import dispatch

logger = structlog.get_logger(__name__)

SEED_FILE = Path(__file__).with_name("seed_problems.json")
RUNS_PER_MINUTE = 20  # "Run" (visible tests only); submissions have their own limit


class RateLimitedError(AppError):
    status_code = 429
    code = "rate_limited"


# ------------------------------------------------------------------ languages


async def ensure_languages(session: AsyncSession) -> None:
    """Insert missing default languages. Concurrent callers may race to insert the same
    row; each insert gets its own savepoint so the loser just skips it."""
    existing = set(await session.scalars(select(Language.key)))
    for spec in DEFAULT_LANGUAGES:
        if spec["key"] not in existing:
            try:
                async with session.begin_nested():
                    session.add(Language(**spec))
            except IntegrityError:
                pass


async def list_languages(session: AsyncSession, *, enabled_only: bool = True) -> list[Language]:
    await ensure_languages(session)
    stmt = select(Language).order_by(Language.sort_order)
    if enabled_only:
        stmt = stmt.where(Language.enabled.is_(True))
    return list(await session.scalars(stmt))


async def get_language(session: AsyncSession, key: str) -> Language:
    language = await session.get(Language, key)
    if language is None or not language.enabled:
        raise AppError(f"'{key}' isn't an available language.", code="invalid_language")
    return language


def starter_for(question: Question, language_key: str) -> str:
    template = next((t for t in question.templates if t.language_key == language_key), None)
    return template.starter_code if template and template.starter_code else STARTERS[language_key]


# ------------------------------------------------------------------ seed


async def seed_problems(session: AsyncSession) -> int:
    """Insert the shipped problems that are missing (by slug). Never overwrites edits."""
    await ensure_languages(session)
    existing = set(await session.scalars(select(Question.slug)))
    created = 0
    for spec in json.loads(SEED_FILE.read_text(encoding="utf-8")):
        if spec["slug"] in existing:
            continue
        question = Question(
            slug=spec["slug"],
            title=spec["title"],
            difficulty=Difficulty(spec["difficulty"]),
            topics=spec["topics"],
            statement=spec["statement"],
            status=QuestionStatus.PUBLISHED,
            source="seed",
            validation={"ok": True, "at": datetime.now(UTC).isoformat(), "details": [],
                        "note": "Expected outputs were generated by the reference solution."},
        )  # fmt: skip
        question.templates = [
            QuestionTemplate(language_key=key, starter_code=STARTERS[key], reference_solution=code)
            for key, code in spec["reference"].items()
        ]
        question.tests = [TestCase(**t) for t in spec["tests"]]
        session.add(question)
        created += 1
    await session.flush()
    return created


# ------------------------------------------------------------------ problems (users)


@dataclass
class ProblemRow:
    question: Question
    solved: bool
    attempted: bool


async def list_problems(
    session: AsyncSession,
    user: User,
    *,
    difficulty: Difficulty | None = None,
    topic: str | None = None,
) -> list[ProblemRow]:
    stmt = select(Question).where(Question.status == QuestionStatus.PUBLISHED)
    if difficulty:
        stmt = stmt.where(Question.difficulty == difficulty)
    questions = list(await session.scalars(stmt.order_by(Question.difficulty, Question.title)))
    if topic:
        questions = [q for q in questions if topic in q.topics]
    rows = await session.execute(
        select(
            Submission.question_id,
            func.max(case((Submission.verdict == Verdict.ACCEPTED, 1), else_=0)),
        )
        .where(Submission.user_id == user.id)
        .group_by(Submission.question_id)
    )
    progress = {qid: bool(solved) for qid, solved in rows}
    return [ProblemRow(q, progress.get(q.id, False), q.id in progress) for q in questions]


async def get_problem(
    session: AsyncSession, slug: str, *, include_drafts: bool = False
) -> Question:
    question = await session.scalar(select(Question).where(Question.slug == slug))
    if question is None or (not include_drafts and question.status != QuestionStatus.PUBLISHED):
        raise NotFoundError("Problem not found")
    return question


_recent_runs: dict[uuid.UUID, deque[float]] = defaultdict(deque)


def _check_run_rate(user: User) -> None:
    """In-process sliding window (Phase 9 moves rate limits to Redis)."""
    now = time.monotonic()
    window = _recent_runs[user.id]
    while window and now - window[0] > 60:
        window.popleft()
    if len(window) >= RUNS_PER_MINUTE:
        raise RateLimitedError("You're running code very quickly. Wait a few seconds.")
    window.append(now)


async def run_examples(
    session: AsyncSession, user: User, question: Question, language_key: str, code: str
) -> Grade:
    """Run against the visible tests only (fast feedback; nothing is stored)."""
    _check_run_rate(user)
    language = await get_language(session, language_key)
    visible = [t for t in question.tests if not t.hidden]
    return await grade(language, code, visible)


async def submit(
    session: AsyncSession,
    user: User,
    question: Question,
    language_key: str,
    code: str,
    idempotency_key: str | None,
) -> Submission:
    """Queue a graded submission against all tests. Repeating a request with the same
    Idempotency-Key returns the original submission instead of grading twice."""
    if idempotency_key:
        existing = await session.scalar(
            select(Submission).where(
                Submission.user_id == user.id, Submission.idempotency_key == idempotency_key
            )
        )
        if existing is not None:
            return existing
    await get_language(session, language_key)
    limit = get_settings().submissions_per_minute
    recent = await session.scalar(
        select(func.count())
        .select_from(Submission)
        .where(
            Submission.user_id == user.id,
            Submission.created_at >= datetime.now(UTC) - timedelta(minutes=1),
        )
    )
    if (recent or 0) >= limit:
        raise RateLimitedError(f"You can submit {limit} times a minute. Try again shortly.")
    submission = Submission(
        user_id=user.id,
        question_id=question.id,
        language_key=language_key,
        code=code,
        verdict=Verdict.QUEUED,
        total=len(question.tests),
        idempotency_key=idempotency_key,
    )
    session.add(submission)
    await session.commit()
    from app.modules.coding import tasks

    dispatch(tasks.grade_submission, grade_submission_job, str(submission.id))
    return submission


async def grade_submission_job(submission_id: str) -> None:
    async with session_factory()() as session:
        submission = await session.get(Submission, uuid.UUID(submission_id))
        if submission is None or submission.verdict not in (Verdict.QUEUED, Verdict.RUNNING):
            return
        question = await session.get(Question, submission.question_id)
        language = await session.get(Language, submission.language_key)
        if question is None or language is None:
            submission.verdict = Verdict.SANDBOX_ERROR
            await session.commit()
            return
        submission.verdict = Verdict.RUNNING
        tests = list(question.tests)
        await session.commit()  # nothing held open while the sandbox runs
        result = await grade(language, submission.code, tests)
        submission.verdict = result.verdict
        submission.passed = result.passed
        submission.total = result.total
        submission.results = result.results
        submission.compile_output = result.compile_output
        submission.max_time_ms = result.max_time_ms
        submission.finished_at = datetime.now(UTC)
        await session.commit()
        logger.info("submission_graded", submission_id=submission_id, verdict=result.verdict.value)


async def get_submission(session: AsyncSession, user: User, submission_id: uuid.UUID) -> Submission:
    submission = await session.get(Submission, submission_id)
    if submission is None or submission.user_id != user.id:
        raise NotFoundError("Submission not found")
    return submission


async def my_submissions(session: AsyncSession, user: User, question: Question) -> list[Submission]:
    return list(
        await session.scalars(
            select(Submission)
            .where(Submission.user_id == user.id, Submission.question_id == question.id)
            .order_by(Submission.created_at.desc())
            .limit(20)
        )
    )


# ------------------------------------------------------------------ question bank (admin)


async def validate_question(session: AsyncSession, question: Question) -> dict[str, Any]:
    """Run every reference solution against every test in the sandbox. A question can
    only be published when all of them pass."""
    details: list[dict[str, Any]] = []
    references = [t for t in question.templates if t.reference_solution]
    tests = list(question.tests)
    for template in references:
        language = await session.get(Language, template.language_key)
        if language is None:
            continue
        result = await grade(language, template.reference_solution or "", tests)
        details.append(
            {
                "language": template.language_key,
                "verdict": result.verdict.value,
                "passed": result.passed,
                "total": result.total,
                "max_time_ms": result.max_time_ms,
                "failures": [r for r in result.results if r["verdict"] != Verdict.ACCEPTED][:3],
            }
        )
    problems = []
    if not references:
        problems.append("Add a reference solution in at least one language.")
    if not any(not t.hidden for t in tests):
        problems.append("Add at least one visible example test.")
    if not any(t.hidden for t in tests):
        problems.append("Add at least one hidden test.")
    ok = not problems and all(d["verdict"] == Verdict.ACCEPTED for d in details)
    report = {
        "ok": ok,
        "at": datetime.now(UTC).isoformat(),
        "details": details,
        "problems": problems,
    }
    question.validation = report
    return report


def publishable(question: Question) -> None:
    if not (question.validation or {}).get("ok"):
        raise ConflictError(
            "Validate the question first: every reference solution must pass every test.",
            code="not_validated",
        )


async def question_stats(
    session: AsyncSession, question_ids: list[uuid.UUID]
) -> dict[uuid.UUID, dict[str, Any]]:
    """Attempts, acceptance rate and solvers per question, to spot too-easy/too-hard ones."""
    if not question_ids:
        return {}
    rows = await session.execute(
        select(
            Submission.question_id,
            func.count(),
            func.sum(case((Submission.verdict == Verdict.ACCEPTED, 1), else_=0)),
            func.count(func.distinct(Submission.user_id)),
            func.avg(Submission.max_time_ms),
        )
        .where(Submission.question_id.in_(question_ids))
        .group_by(Submission.question_id)
    )
    return {
        qid: {
            "submissions": total,
            "accepted": int(accepted or 0),
            "acceptance_rate": round((accepted or 0) / total, 3) if total else None,
            "users": users,
            "avg_time_ms": round(avg) if avg is not None else None,
        }
        for qid, total, accepted, users, avg in rows
    }
